# Dart / Flutter 静的解析設定
# https://dart.dev/guides/language/analysis-options
include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    # import 順序の警告を error に昇格
    directives_ordering: warning
  exclude:
    - "**/*.g.dart"
    - "build/**"

linter:
  rules:
    # ── 型安全 ──
    always_declare_return_types: true
    avoid_dynamic_calls: true
    # prefer_const_constructors は既存コードに大量の info を出すため段階的に対応
    # prefer_const_constructors: true
    prefer_const_declarations: true

    # ── 可読性 ──
    prefer_single_quotes: true
    sort_constructors_first: true
    unawaited_futures: true
    prefer_final_local_variables: true
    directives_ordering: true

    # ── 安全性 ──
    cancel_subscriptions: true
    close_sinks: true
    avoid_print: true
    no_duplicate_case_values: true
    valid_regexps: true
